//! Generates the `BUNDLED` table from whatever is in `assets/anim/`.
//!
//! Adding an animation used to mean writing one `include_str!` per frame by
//! hand, which is tedious and easy to get wrong: a missed frame, a stale entry
//! after a rename. Now the directory is the source of truth, and dropping a
//! folder in is the whole job.
//!
//! It also fixes a trap. `include_str!` alone does not make cargo rebuild when
//! only the art changes, so editing a frame and running `cargo test` could
//! silently test the previous binary. The `rerun-if-changed` lines below cover
//! every frame, so that cannot happen.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

fn main() {
    let root = Path::new("assets/anim");
    println!("cargo:rerun-if-changed=assets/anim");

    let mut animations: Vec<(String, Vec<String>)> = Vec::new();
    collect(root, &mut animations);

    if animations.is_empty() {
        panic!("no animations found under {}", root.display());
    }

    // Sorted so the generated file is stable between builds on machines whose
    // directory order differs.
    animations.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// Generated by build.rs from assets/anim. Do not edit.\n\
         const BUNDLED: &[(&str, &[&str])] = &[\n",
    );
    for (name, frames) in &animations {
        let _ = write!(out, "    (\n        {name:?},\n        &[\n");
        for f in frames {
            let _ = writeln!(
                out,
                "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{f}\")),"
            );
        }
        out.push_str("        ],\n    ),\n");
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("bundled.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// Every directory holding `.txt` frames, at any depth.
///
/// Nesting is allowed so art can be filed by category: `anim/animals/cat-run`
/// and `anim/space/saturn` both work. The animation is named after its leaf
/// directory, not its path, so `-a cat-run` keeps working wherever the folder
/// is moved to.
fn collect(dir: &Path, out: &mut Vec<(String, Vec<String>)>) {
    let entries = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()));

    let mut frames: Vec<String> = Vec::new();
    let mut subdirs: Vec<std::path::PathBuf> = Vec::new();

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            subdirs.push(path);
        } else if path.extension().is_some_and(|e| e == "txt") {
            frames.push(path.to_string_lossy().replace('\\', "/"));
        }
    }

    // Filename order is frame order, which is why the art is named 00, 01, 02
    // rather than 1, 2, 3.
    frames.sort();

    if !frames.is_empty() {
        let name = dir
            .file_name()
            .expect("animation directory has a name")
            .to_string_lossy()
            .into_owned();

        if let Some((other, _)) = out.iter().find(|(n, _)| *n == name) {
            panic!(
                "two animations are both named {other:?}; leaf directory names \
                 are the animation names, so they have to be unique"
            );
        }

        for f in &frames {
            println!("cargo:rerun-if-changed={f}");
        }
        out.push((name, frames));
    }

    // A directory can hold frames and still have children; both are scanned.
    subdirs.sort();
    for sub in subdirs {
        collect(&sub, out);
    }
}
